import os
import json
import subprocess
from datetime import datetime
from core.logger import logger
from core.skills.wrapper import agent_tool

@agent_tool
def bootstrap_autonomous_project(project_name: str, path: str = ".", **kwargs) -> str:
    """
    Standard 2026 Architect Mode. 
    Generates structure, Git, CI/CD, Docker, and .axis_context for a new ecosystem.
    """
    project_root = os.path.abspath(os.path.join(path, project_name))
    logger.info("architect.bootstrap_start", name=project_name, path=project_root)
    
    if os.path.exists(project_root):
        return f"❌ [ARCHITECT]: Directory '{project_name}' already exists. Aborting to prevent overwrite."

    try:
        # 1. Core Structure
        folders = [
            "src", "tests", "docs", "scripts", "configs",
            ".github/workflows", "docker"
        ]
        for folder in folders:
            os.makedirs(os.path.join(project_root, folder), exist_ok=True)
            
        # 2. Base Files
        files = {
            "README.md": f"# {project_name}\n\nGenerated by AXIS v3.2 'Architect Mode'.\n\n## 🚀 Getting Started\n- Run `npm install` or `pip install`...",
            "PROJECT_SNAPSHOT.md": f"# {project_name} Snapshot\n\nRoot: {project_root}",
            ".axis_context": json.dumps({
                "project_name": project_name,
                "version": "1.0.0",
                "status": "active",
                "created_at": str(datetime.now()),
                "architect_version": "2026.1",
                "features": ["CI/CD", "Docker", "Auto-Monitoring"]
            }, indent=2),
            "docker/Dockerfile": "FROM python:3.11-slim\nWORKDIR /app\nCOPY . .\nCMD [\"python\", \"src/main.py\"]",
            ".github/workflows/ci.yml": "name: CI\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Run Tests\n        run: pytest"
        }
        
        for file_path, content in files.items():
            full_path = os.path.join(project_root, file_path)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content)
                
        # 3. Initialization Logic
        # Try to init git
        try:
            subprocess.run(["git", "init"], cwd=project_root, capture_output=True, check=True)
            with open(os.path.join(project_root, ".gitignore"), "w") as f:
                f.write("__pycache__/\n*.pyc\nvenv/\n.env\n")
        except:
            logger.warning("architect.git_init_failed")
            
        logger.info("architect.bootstrap_success", name=project_name)
        return f"✅ [ARCHITECT]: Project '{project_name}' successfully bootstrapped at {project_root}.\nAdded structure, Git, CI/CD, and .axis_context."

    except Exception as e:
        logger.error("architect.bootstrap_error", error=str(e))
        return f"❌ [ARCHITECT]: Bootstrap failed: {str(e)}"

EXPORTED_TOOLS = [bootstrap_autonomous_project]
